# .github/workflows/readme-actions.yml
name: README Actions

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: highlyavailable/github-readme-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: 'highlyavailable'
          ACTION_TYPE: 'pinned_prs'
          START_DATE: '2025-05-01'
          PR_STATE: 'merged'
          MAX_LINES: 15